# Use an official Python runtime as a base image
FROM continuumio/anaconda

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
ADD . /app

# Run app.py when the container launches
CMD [bash]
